import type { Metadata } from "next";
import {
  Hind_Siliguri,
  Noto_Sans_Bengali as Noto,
  Poppins,
} from "next/font/google";
import { Toaster } from "react-hot-toast";

import NextAuthProvider from "@/lib/Provider";
import QueryProvider from "@/lib/QueryClientProvider";
import ReduxProvider from "@/lib/reduxProvider";
import { cn } from "@/lib/utils";
import "./globals.css";

const poppin = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});
const bangli = Noto({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-noto",
});
const hind_siliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-siliguri",
});

export const metadata: Metadata = {
  title: "Flex LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          poppin.className,
          bangli.variable,
          hind_siliguri.variable
        )}
      >
<<<<<<< HEAD
        <QueryProvider>
          <NextAuthProvider>
            <ReduxProvider>
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </ReduxProvider>
          </NextAuthProvider>
        </QueryProvider>
=======
        <NextAuthProvider>
          <ReduxProvider>
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </ReduxProvider>
        </NextAuthProvider>
>>>>>>> 298d295 ([change] auth functionality)
      </body>
    </html>
  );
}
